export { default as Logo } from './Logo.svg';
export { default as Cloud } from './Cloud.svg';
export { default as Cloud2 } from './Cloud2.svg';
export { default as Frame } from './Frame.svg';
export { default as HeroPicksBuildings } from './HeroPicksBuildings.svg';
export { default as Destination } from './Destination.svg';
export { default as LowestPrice } from './LowestPrice.svg';
export { default as Receipt } from './Receipt.svg';
export { default as BuildingsHero } from './BuildingsHero.svg';
